// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BingoCard struct {
	Numbers []int `json:"numbers"`
}

type User struct {
	Name string `json:"name"`
	Code int    `json:"code"`
}

type ValidateResult struct {
	IsValid *bool `json:"isValid"`
}
