package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"bingo/graph/generated"
	"bingo/graph/model"
	"bingo/internal/app/bingoCard"
	"bingo/pkg/jwt"
	"context"
	"fmt"
	"log"

	"go.mongodb.org/mongo-driver/mongo"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (string, error) {
	log.Printf("login(name: %s, code: %d)", input.Name, input.Code)

	// query user
	user, err := r.userRepository.FindUserByCode(input.Code)
	if err == mongo.ErrNoDocuments {
		log.Printf("Code not found %s", input.Code)
		return "", fmt.Errorf("Code not correct")
	}
	if err != nil {
		fmt.Printf("MongoDB error: %s", err)
		return "", fmt.Errorf("System Error occur.")
	}

	// check account name password
	if user.Name == "" {
		// update account info
		user.Name = input.Name
		user.Numbers = bingoCard.GenBingoCard()
		if err := r.userRepository.Update(user); err != nil {
			fmt.Printf("MongoDB update error: %s", err)
			return "", fmt.Errorf("System Error occur.")
		}

		token, err := jwt.GenToken(user.ID.Hex(), input.Name)
		if err != nil {
			log.Printf("Gen Token Error: %v", err)
			return "", err
		} else {
			return token, nil
		}
	} else if user.Name == input.Name && user.Code == input.Code {
		token, err := jwt.GenToken(user.ID.Hex(), input.Name)
		if err != nil {
			log.Printf("Gen Token Error: %v", err)
			return "", err
		} else {
			return token, nil
		}
	}

	return "", fmt.Errorf("Username or Code not correct")
}

// LoginAdmin is the resolver for the loginAdmin field.
func (r *queryResolver) LoginAdmin(ctx context.Context, input *model.LoginInput) (string, error) {
	// query user
	user, err := r.userRepository.FindUserByName(input.Name)
	if err == mongo.ErrNoDocuments {
		log.Printf("Name not found %s", input.Name)
		return "", fmt.Errorf("Code not correct")
	}
	if err != nil {
		fmt.Printf("MongoDB error: %s", err)
		return "", fmt.Errorf("System Error occur.")
	}

	if user.Name == input.Name && user.Code == input.Code {
		token, err := jwt.GenToken(user.ID.Hex(), input.Name)
		if err != nil {
			log.Printf("Gen Token Error: %v", err)
			return "", err
		} else {
			return token, nil
		}
	}
	return "", fmt.Errorf("Username or Password not correct")
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
