package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"bingo/graph/model"
	"bingo/internal/app/bingoCard"
	"bingo/internal/middlewares/auth"
	"context"
	"fmt"
	"log"

	"go.mongodb.org/mongo-driver/mongo"
)

// AddLotteryNumber is the resolver for the addLotteryNumber field.
func (r *mutationResolver) AddLotteryNumber(ctx context.Context, number int) (int, error) {
	return bingoCard.AddLotteryNumber(number), nil
}

// ResetLottery is the resolver for the resetLottery field.
func (r *mutationResolver) ResetLottery(ctx context.Context) (bool, error) {
	return bingoCard.ResetLottery(), nil
}

// BingoCard is the resolver for the bingoCard field.
func (r *queryResolver) BingoCard(ctx context.Context) (*model.BingoCard, error) {
	userId := auth.ForContext(ctx)
	if userId == nil {
		return &model.BingoCard{}, fmt.Errorf("Access Denied")
	}
	log.Printf("User Login with id: %s, name: %s", userId.Id, userId.Name)

	// query user
	user, err := r.userRepository.FindUserByID(userId.Id)
	if err == mongo.ErrNoDocuments {
		log.Printf("No document was found with id %s", userId.Id)
		return nil, fmt.Errorf("Please login again.")
	}
	if err != nil {
		fmt.Printf("MongoDB error: %s", err)
		return nil, fmt.Errorf("System Error occur.")
	}

	if user.Numbers != nil {
		return &model.BingoCard{Numbers: user.Numbers}, nil
	}
	return nil, fmt.Errorf("System Error occur.")
}

// ValidateCard is the resolver for the validateCard field.
func (r *queryResolver) ValidateCard(ctx context.Context, id string) (*model.ValidateResult, error) {
	log.Printf("ValidateCard(id: %s)", id)

	// query user
	user, err := r.userRepository.FindUserByID(id)
	if err == mongo.ErrNoDocuments {
		log.Printf("No document was found with id %s", id)
		return nil, fmt.Errorf("Please login again.")
	}
	if err != nil {
		fmt.Printf("MongoDB error: %s", err)
		return nil, fmt.Errorf("System Error occur.")
	}

	if user.Numbers != nil {
		validBingo := bingoCard.ValidateBingoCard(user.Numbers)
		return validBingo, nil
	}
	return nil, fmt.Errorf("System Error occur.")
}
